config/routes.rb
Rails.application.routes.draw do

  mount ReactiveRecord::Engine => '/rr'

  devise_for :users

  root 'home#show'
  resources :tchats, only: [:index]
  resources :messengers, only: [:index]

end

app/models/_react_public_models.rb
# app/models/_react_public_models.rb
require_tree './public'

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  layout :layout_by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def layout_by_resource
    if devise_controller?
      "devise_template"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :nickname, :firstname, :lastname, :function ])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/messengers_controller.rb
class MessengersController < ApplicationController
  def index
  end
end

app/controllers/tchats_controller.rb
class TchatsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messengers_helper.rb
module MessengersHelper
end

app/helpers/tchats_helper.rb
module TchatsHelper
end

app/views/home/show.html.erb
<div class="row">

  <div class="col-md-3 nav-fixed">
    <div class="row">
      <div class="col-md-12">
        <!-- Begin user profile -->
        <%= react_component "ProfileUser", current_user: current_user, post: Post.new, comment: Comment.new %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
          <!-- Begin Members -->
          <%= react_component "CounterMembers", user: User.new %>
      </div>
    </div>
  </div><!-- end .col-md-3 nav-fixed -->

  <div class="col-md-9">
    <%= react_component "Store", current_user: current_user %>
  </div><!-- end .col-md-9 -->

</div>



<!-- <div class="row">
<div class="col-md-12">
<div class="box box-widget widget-user-2">
<div class="widget-user-header bg-yellow">
<h3 class="widget-user-username">Nos meilleurs bloggers !!!</h3>
</div>
<div class="box-footer no-padding">
<ul class="nav nav-stacked">
<li><a href="#">Projects <span class="pull-right badge bg-blue">31</span></a></li>
<li><a href="#">Tasks <span class="pull-right badge bg-aqua">5</span></a></li>
<li><a href="#">Completed Projects <span class="pull-right badge bg-green">12</span></a></li>
<li><a href="#">Followers <span class="pull-right badge bg-red">842</span></a></li>
</ul>
</div>
</div>
</div>
</div> -->

app/views/layouts/_damned.html.erb
<div class="row">
  <div class="col-md-12 panneau-accueil vertical-center">
    <div class="damned">
      <div class="row">
        <div class="col-md-3 col-md-offset-2">
          <div class="header-content-inner">
            <img class="img-responsive" src="http://bootdey.com/img/Content/fdfadfadsfadoh.png">
          </div>
        </div>
        <div class="col-md-5 col-md-offset-1">
          <h1>666 !!! Damned !!!</h1>
          <h2>Cette partie sera développée prochainement.</h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2015
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_connection.html.erb
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">REACTRB DEMOS</a>
    </div>

  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">ReactRb DEMOS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to "<i class='fa fa-comment'></i>BLOG".html_safe, root_path %></li>
        <li class="<%= 'active' if params[:controller] == 'tchats' %>"><%= link_to "<i class='fa fa-comments'></i>TCHAT".html_safe, tchats_path %></li>
        <li class="<%= 'active' if params[:controller] == 'messengers' %>"><%= link_to "<i class='fa fa-comments-o'></i>MESSENGER".html_safe, messengers_path %></li>
        <li><%= link_to "<i class='fa fa-sign-out'></i>QUITTER".html_safe, destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <span>
            <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
          </span>
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
              <span class="block m-t-xs">
                <strong class="font-bold">David Williams</strong>
              </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a href="">Profile</a>
            </li>
            <li><a href="">Contacts</a>
            </li>
            <li><a href="">Mailbox</a>
            </li>
            <li class="divider"></li>
            <li><a href="">Logout</a>
            </li>
          </ul>
        </div>
        <div class="logo-element">
          IN+
        </div>
      </li>

      <li>
        <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label">Menu Levels </span><span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="#">Third Level <span class="fa arrow"></span></a>
            <ul class="nav nav-third-level">
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>

            </ul>
          </li>
          <li><a href="#">Second Level Item</a></li>
          <li>
            <a href="#">Second Level Item</a></li>
            <li>
              <a href="#">Second Level Item</a></li>
            </ul>
          </li>
          <li class="">
            <i class="fa fa-magic"></i> <span class="nav-label">CSS Animations </span><span class="label label-info pull-right">62</span>

          </li>
          <li class="landing_link">
            <i class="fa fa-star"></i> <span class="nav-label">Landing page </span>

          </li>
        </ul>

      </div>
    </nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search"/>
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="pull-left">
                                <img alt="image" class="img-circle" src="<%= image_path('a7.jpg') %>" />
                            </a>
                            <div class="media-body">
                                <small class="pull-right">46h ago</small>
                                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br/>
                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="pull-left">
                                <img alt="image" class="img-circle" src="<%= image_path('a4.jpg') %>" />
                            </a>
                            <div class="media-body ">
                                <small class="pull-right text-navy">5h ago</small>
                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br/>
                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="#" class="pull-left">
                                <img alt="image" class="img-circle" src="<%= image_path('profile.jpg') %>" />
                            </a>
                            <div class="media-body ">
                                <small class="pull-right">23h ago</small>
                                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br/>
                                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>


            <li>
                <i class="fa fa-sign-out"></i> Log out
            </a>
        </li>

            <li>
                <a class="right-sidebar-toggle">
                    <i class="fa fa-tasks"></i>
                </a>
            </li>
    </ul>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reactrb - TestBlog</title>
  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Wrapper-->
  <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

    <!-- Navigation -->
    <%= render 'layouts/navigation' %>

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

      <!-- Page wrapper -->
      <%= render 'layouts/topnavbar' %>

      <!-- Main view  -->
      <%= yield %>

      <!-- Footer -->
      <%= render 'layouts/footer' %>

    </div>
    <!-- End page wrapper-->

    <!-- Right sidebar -->
    <%= render 'layouts/rightsidebar' %>

  </div>
  <!-- End wrapper-->

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <!-- Include javascript per-view -->
  <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
  <%= yield :javascript %>

</body>
</html>

app/views/layouts/devise_template.html.erb
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reactrb - TestBlog</title>
    <meta name="description" content="">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="login-devise">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <!-- Placeholder for IE9 -->
    <!--[if IE 9 ]>
      <script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
    <![endif]-->
  </body>
</html>

app/views/messengers/index.html.erb
<%= render 'layouts/damned' %>

app/views/tchats/index.html.erb
<%= render 'layouts/damned' %>